version: '3.8'

services:
  storypolisher:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - API_KEY=${API_KEY}
    restart: unless-stopped
  
  test:
    build: .
    volumes:
      - .:/app
    environment:
      - API_KEY=${API_KEY}
    command: pytest -v
